Repository Yuba-Technology/Archives, pull requests merged in 2024-03, with the labels that each got.

#4 Dev/initial web
  .editorconfig
  .github/CODEOWNERS
  .github/workflows/web.yml
  .gitignore
  .prettierrc.json
  .vscode/extensions.json
  .vscode/settings.json
  jsconfig.json
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/robots.txt
  src/assets/images/archives-logo-text.svg
  src/assets/images/archives-stamp.svg
  src/web/index.js
  src/web/index.vue
  src/web/webpack.common.js
  src/web/webpack.dev.js
  src/web/webpack.prod.js
Labels: CI, frontend

#5 Dev/initial server
  .editorconfig
  .eslintignore
  .eslintrc.cjs
  .github/.git_commit_template.txt
  .github/CONTRIBUTING.md
  .github/SUPPORT.md
  .prettierrc.json
  .vscode/settings.json
  package-lock.json
  package.json
  public/index.html
  src/web/index.js
  src/web/index.vue
  src/web/webpack.common.js
  src/web/webpack.dev.js
  src/web/webpack.prod.js
Labels: CI, backend, build

#6 Create codeql.yml
  .github/workflows/codeql.yml
Labels: CI, github-actions, build

#8 Docs(README): Add README.md and under-construction.gif files
  README.md
  src/assets/images/under-construction.gif
Labels: documentation

#9 Chore: Dev/initial build js development environment
  .babelrc.js
  .eslintrc.cjs
  .github/CODEOWNERS
Labels: CI, frontend, build

#10 Refactor(webpack): Move webpack config files to root dir `./`
  .eslintrc.cjs
  package.json
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: CI, build

#12 Fix(ESLint): ESLint does not work
  .eslintrc.cjs
  .github/workflows/lint.yml
  package-lock.json
  package.json
Labels: bug, CI, p2, tests

#13 Chore: Update ESLint and webpack configurations
  .eslintrc.cjs
  jsconfig.json
  package-lock.json
  package.json
  webpack.common.js
Labels: CI, build, tests

#14 Refactor/logo
  src/assets/images/archives-logo-text.svg
  src/assets/images/archives-stamp.svg
  src/web/components/languages/config.js
  src/web/components/languages/language.js
Labels: design, refactoring

#15 Feat: i18n
  .babelrc.js
  .eslintrc.cjs
  .github/PULL_REQUEST_TEMPLATE.md
  TESTS/web/unit/languages/languages.test.js
  jest.config.js
  package-lock.json
  package.json
  src/assets/locales/en-US.yml
  src/assets/locales/zh-CN.yml
  src/web/components/languages/language.js
Labels: CI, feature, frontend, release-highlight, p2, tests
